spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB